name: readme_app
description: "Listen to your texts"
publish_to: 'none'
version: 0.1.0+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  receive_sharing_intent: ^1.6.7
  audioplayers: 5.2.1 # Use the latest version available
  cloud_firestore: ^4.15.5
  firebase_crashlytics: ^3.4.15
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  cloud_functions: ^4.6.5
  provider: ^6.1.1
  intl: ^0.18.1
  feedback: ^3.0.1
  smooth_page_indicator: ^1.1.0
  firebase_storage: ^11.6.10
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  webview_flutter: ^4.7.0
  chaleno: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/introslides/
    - assets/gifs/
