name: readme_app
description: "Listen to your texts"
publish_to: 'none'
version: 0.1.0+14

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  receive_sharing_intent: ^1.8.0
  audioplayers: ^6.0.0
  cloud_firestore: ^5.1.0
  firebase_crashlytics: ^4.0.3
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.2.0
  cloud_functions: ^5.0.3
  provider: ^6.1.2
  intl: ^0.18.1
  feedback: ^3.1.0
  smooth_page_indicator: ^1.2.0
  firebase_storage: ^12.1.1
  google_fonts: ^6.2.1
  just_audio: ^0.9.39
  webview_flutter: ^4.8.0
  chaleno: ^0.0.8
  url_launcher: ^6.3.0
  app_links: ^6.1.4
  flutter_secure_storage: ^9.2.2
  audio_service: ^0.18.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/introslides/
    - assets/gifs/
