// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7x8Eq1Zvo-pZwZA4nD3trCnujh0mcBA0',
    appId: '1:431185867269:web:add6e32a2b640214efe26c',
    messagingSenderId: '431185867269',
    projectId: 'firebase-readme-123',
    authDomain: 'fir-readme-123.firebaseapp.com',
    storageBucket: 'firebase-readme-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD710uAbznLwYdW_JDTG3m-YXF0DOWKZvE',
    appId: '1:431185867269:android:03d48799e3688c83efe26c',
    messagingSenderId: '431185867269',
    projectId: 'firebase-readme-123',
    storageBucket: 'firebase-readme-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8CJtX1e8SfyxKawC0tyDpMtG65JxPUxU',
    appId: '1:431185867269:ios:6f3b692e2e9d0bf0efe26c',
    messagingSenderId: '431185867269',
    projectId: 'firebase-readme-123',
    storageBucket: 'firebase-readme-123.appspot.com',
    iosBundleId: 'com.example.readmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8CJtX1e8SfyxKawC0tyDpMtG65JxPUxU',
    appId: '1:431185867269:ios:b02255a545256388efe26c',
    messagingSenderId: '431185867269',
    projectId: 'firebase-readme-123',
    storageBucket: 'firebase-readme-123.appspot.com',
    iosBundleId: 'com.example.readmeApp.RunnerTests',
  );
}
